d-build:
	sudo docker build -t frontend -f Dockerfile.dev .
p-build:
	sudo docker build -t storefront:v0.1.0 .

run-front-d:
	cd ../ && $(MAKE) run-front-d
run-front:
	cd ../ && $(MAKE) run-front

rmi:
	sudo docker rmi frontend
img:
	cd ../ && $(MAKE) img

ps:
	cd ../ && $(MAKE) ps
nls:
	cd ../ && $(MAKE) nls

emg:
	cd ../ && $(MAKE) emg
e-api:
	cd ../ && $(MAKE) e-api
e-front:
	cd ../ && $(MAKE) e-front

pr:
	cd ../ && $(MAKE) pr
ipr:
	cd ../ && $(MAKE) ipr
cpr:
	cd ../ && $(MAKE) cpr
vpr:
	cd ../ && $(MAKE) vpr
npr:
	cd ../ && $(MAKE) npr

up:
	cd ../ && $(MAKE) up
up-p:
	cd ../ && $(MAKE) up-p
dcs:
	cd ../ && $(MAKE) dcs
dcd:
	cd ../ && $(MAKE) dcd
