version: "3.8"

services:
  mongodb:
    image: mongo:4-bionic
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - store-tier
    volumes:
      - store-db:/data/db

  api:
    image: backend:v0.1.0
    container_name: api
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - store-tier
    volumes:
      - ./backend:/usr/src/backend
      - /usr/src/backend/node_modules
    depends_on:
      - mongodb

  storefront:
    image: frontend:v0.1.0
    container_name: front
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - store-tier
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
    depends_on:
      - api

volumes:
  store-db:

networks:
  store-tier:
    driver: bridge
