d-build:
	sudo docker build -t backend -f Dockerfile.dev .
p-build:
	sudo docker build -t api:v0.1.0 .

run-api-d:
	cd ../ && $(MAKE) run-api-d
run-api:
	cd ../ && $(MAKE) run-api

rmi:
	sudo docker rmi backend
img:
	cd ../ && $(MAKE) img

ps:
	cd ../ && $(MAKE) ps
nls:
	cd ../ && $(MAKE) nls

emg:
	cd ../ && $(MAKE) emg
e-api:
	cd ../ && $(MAKE) e-api
e-front:
	cd ../ && $(MAKE) e-front

pr:
	cd ../ && $(MAKE) pr
ipr:
	cd ../ && $(MAKE) ipr
cpr:
	cd ../ && $(MAKE) cpr
vpr:
	cd ../ && $(MAKE) vpr
npr:
	cd ../ && $(MAKE) npr

up:
	cd ../ && $(MAKE) up
up-p:
	cd ../ && $(MAKE) up-p
dcs:
	cd ../ && $(MAKE) dcs
dcd:
	cd ../ && $(MAKE) dcd
